import Head from "next/head";
import "@src/styles/globals.css";
import type { AppProps } from "next/app";
import localFont from "@next/font/local";
import AuthProvider from "@src/shared/provider/AuthProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const poppins = localFont({
  src: [
    { path: "./fonts/poppins/Poppins-Regular.ttf", weight: "400" },
    { path: "./fonts/poppins/Poppins-Medium.ttf", weight: "500" },
    { path: "./fonts/poppins/Poppins-SemiBold.ttf", weight: "600" },
    { path: "./fonts/poppins/Poppins-Bold.ttf", weight: "700" },
  ],
  variable: "--font-poppins",
});

export default function App({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();
  return (
    <main className={poppins.variable}>
      <Head>
        <title>Proedu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <Component {...pageProps} />
        </AuthProvider>
      </QueryClientProvider>
    </main>
  );
}
